### PR TITLE
add travis-ci build status link/image to README

### PR DESCRIPTION
**Pull request by EugenGanshorn**
add travis-ci build status link/image to README

### CODE REVIEW

**Review by nicolashohm — APPROVED** [review]

**Comment by sp4ceb4r** [comment]
@nickel715, sorry I just saw this.

I actually just did something similar and will merge it into master tomorow.

**Comment by nicolashohm** [comment]
@sp4ceb4r ok, I saw your commit, why are you using html in markdown? did you know, travis also provide a button in markdown

**Comment by sp4ceb4r** [comment]
I'm using the html in order to center the buttons. I realize that you can do `alternate` to show the image as well, however that doesn't support centering.

**Comment by EugenGanshorn** [comment]
leave the buttons on the left side, it looks better and is much easier?

**Comment by sp4ceb4r** [comment]
It's cleaner within the markdown itself, but I think in terms of render it's all stylistic preferences.

**Pull request closed without merging**
